"""moderation, verification, push bookkeeping

Revision ID: 43a4e694eec8
Revises: 721d1c6e4bb7
Create Date: 2026-08-13 09:05:32.138891
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '43a4e694eec8'
down_revision: str | None = '721d1c6e4bb7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('gesture', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verifications_status', 'verifications', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_verifications_user_id'), 'verifications', ['user_id'], unique=False)
    op.add_column('chats', sa.Column('last_push_a', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('last_push_b', sa.DateTime(timezone=True), nullable=True))
    # Existing rows need a value before the NOT NULL can hold.
    op.add_column(
        'photos',
        sa.Column(
            'moderation_scores',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column('photos', sa.Column('reviewed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.add_column('photos', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'reviewed_at')
    op.drop_column('photos', 'reviewed_by_id')
    op.drop_column('photos', 'moderation_scores')
    op.drop_column('chats', 'last_push_b')
    op.drop_column('chats', 'last_push_a')
    op.drop_index(op.f('ix_verifications_user_id'), table_name='verifications')
    op.drop_index('ix_verifications_status', table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
