"""user meetups

Revision ID: 44e52617c606
Revises: 9d3a72b0f1c6
Create Date: 2026-08-15 11:09:27.204211
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '44e52617c606'
down_revision: str | None = '9d3a72b0f1c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('thumb_path', sa.String(length=255), nullable=True),
    sa.Column('blur_gradient', sa.String(length=128), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('moderation_reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetups_author_id'), 'meetups', ['author_id'], unique=False)
    op.create_index('ix_meetups_feed', 'meetups', ['city', 'is_active', 'starts_at'], unique=False)
    op.create_table('meetup_responses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('meetup_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meetup_id', 'user_id', name='uq_meetup_responses_pair')
    )
    op.create_index(op.f('ix_meetup_responses_meetup_id'), 'meetup_responses', ['meetup_id'], unique=False)
    op.create_index(op.f('ix_meetup_responses_user_id'), 'meetup_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetup_responses_user_id'), table_name='meetup_responses')
    op.drop_index(op.f('ix_meetup_responses_meetup_id'), table_name='meetup_responses')
    op.drop_table('meetup_responses')
    op.drop_index('ix_meetups_feed', table_name='meetups')
    op.drop_index(op.f('ix_meetups_author_id'), table_name='meetups')
    op.drop_table('meetups')
    # ### end Alembic commands ###
