"""initial schema

Revision ID: 721d1c6e4bb7
Revises: 
Create Date: 2026-08-13 04:13:07.026972
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '721d1c6e4bb7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_events_source_external')
    )
    op.create_index(op.f('ix_events_external_id'), 'events', ['external_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('seeking_gender', sa.String(length=16), nullable=False),
    sa.Column('seeking_age_min', sa.Integer(), nullable=False),
    sa.Column('seeking_age_max', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('interests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('test_answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('test_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_pdn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_photo_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seeking_age_min >= 18', name='ck_users_age_min_18'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_discover', 'users', ['is_active', 'is_banned', 'gender', 'city'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blocked_id', name='uq_blocks_pair')
    )
    op.create_index(op.f('ix_blocks_blocked_id'), 'blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_blocks_user_id'), 'blocks', ['user_id'], unique=False)
    op.create_table('deck_cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('compatibility_pct', sa.SmallInteger(), nullable=False),
    sa.Column('shared_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('scratched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'candidate_id', name='uq_deck_cards_pair')
    )
    op.create_index(op.f('ix_deck_cards_user_id'), 'deck_cards', ['user_id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_sessions_event_id'), 'live_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_user_id'), 'live_sessions', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('compatibility_pct', sa.SmallInteger(), nullable=False),
    sa.Column('shared_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_matches_ordered'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_matches_pair')
    )
    op.create_index(op.f('ix_matches_user_a_id'), 'matches', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_matches_user_b_id'), 'matches', ['user_b_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('thumb_path', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('blur_gradient', sa.String(length=128), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('moderation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'position', name='uq_photos_user_position')
    )
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.String(length=128), nullable=False),
    sa.Column('telegram_charge_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload'),
    sa.UniqueConstraint('telegram_charge_id')
    )
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_table('swipes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'target_id', name='uq_swipes_pair')
    )
    op.create_index(op.f('ix_swipes_actor_id'), 'swipes', ['actor_id'], unique=False)
    op.create_index('ix_swipes_target_action', 'swipes', ['target_id', 'action'], unique=False)
    op.create_index(op.f('ix_swipes_target_id'), 'swipes', ['target_id'], unique=False)
    op.create_table('user_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_events')
    )
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_count_a', sa.Integer(), nullable=False),
    sa.Column('msg_count_b', sa.Integer(), nullable=False),
    sa.Column('revealed_a', sa.Boolean(), nullable=False),
    sa.Column('revealed_b', sa.Boolean(), nullable=False),
    sa.Column('unread_a', sa.Integer(), nullable=False),
    sa.Column('unread_b', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index(op.f('ix_chats_user_a_id'), 'chats', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_chats_user_b_id'), 'chats', ['user_b_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_chat_id_desc', 'messages', ['chat_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_chat_id_desc', table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_user_b_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_user_a_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_swipes_target_id'), table_name='swipes')
    op.drop_index('ix_swipes_target_action', table_name='swipes')
    op.drop_index(op.f('ix_swipes_actor_id'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_matches_user_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_user_a_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_live_sessions_user_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_event_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_deck_cards_user_id'), table_name='deck_cards')
    op.drop_table('deck_cards')
    op.drop_index(op.f('ix_blocks_user_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocked_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index('ix_users_discover', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_external_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
