"""rich messages

Revision ID: d57b1ba4d708
Revises: 44e52617c606
Create Date: 2026-08-16 07:18:22.301646
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd57b1ba4d708'
down_revision: str | None = '44e52617c606'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('reply_to_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.add_column('messages', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('thumb_path', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('blur_gradient', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_id'), 'messages', ['reply_to_id'], unique=False)
    # Имя обязательно: безымянный ключ автогенератор потом не умеет снять,
    # и откат миграции падает на CompileError.
    op.create_foreign_key(
        'fk_messages_reply_to_id', 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_reply_to_id', 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_reply_to_id'), table_name='messages')
    op.drop_column('messages', 'blur_gradient')
    op.drop_column('messages', 'thumb_path')
    op.drop_column('messages', 'file_path')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'edited_at')
    # ### end Alembic commands ###
